### ISSUE TITLE
PHP warnings with debug setting

### ISSUE THREAD

**Issue by tobiasschaeferptb** [joachimruhs/myflat#6]
Hello,

If the debug setting is set to debug I get PHP warnings because of variables that aren't initialized. The TYPO3 version is 12.4 and the myflat version is 1.1.4.
Classes/ViewHelpers/MultiRowCalendarViewHelper.php, line 48:
`		// T. Schaefer: initialize $arrivals and $departures
		$arrivals = [];
		$departures = [];
		for ($i = 0; $i < count($bookings); $i++) {
			
			$arrival = $bookings->toArray()[$i]->getArrival()->getTimestamp();
			$departure = $bookings->toArray()[$i]->getDeparture()->getTimestamp();
			if ( ($arrival > $startOfYear && $arrival < $endOfYear) || ($departure > $startOfYear && $departure < $endOfYear)) {
				$arrivals[$i] = $arrival;
				$departures[$i] = $departure;
				
			}		
			
		}`

Classes/Controller/FlatController.php, line 130:
`	public function availabilitycheckAction() {
		$this->_GP = $this->request->getArguments();
		// T. Schaefer: insert isset
		//if (!$this->_GP['arrival'] || !$this->_GP['departure']) {
		if (!isset($this->_GP['arrival']) || !isset($this->_GP['departure'])) {`

Best regards,
Tobias Schäfer

**Comment by joachimruhs** [comment]
Hi,
I just published version 1.2.0 with bugfix of that.

Regards

**Comment by tobiasschaeferptb** [comment]
Hello,

with version 1.2.0 I still get this PHP warning:
PHP Warning: Undefined array key "arrival" in /typo3conf/ext/myflat/Classes/Controller/FlatController.php line 135
Both files MultiRowCalendarViewHelper.php, line 48 and FlatController.php, line 135 look the same like in version 1.1.4.

Best regards,
Tobias Schäfer

**Comment by joachimruhs** [comment]
I could not reproduce that.
I have implemented your code.
See version 1.2.1
